<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>9e0275cd-ccf4-4d9a-ae77-a747f1412968</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <DocumentationFile>doc.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\.editorconfig" Link=".editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Mapster" Version="7.3.0" />
    <PackageReference Include="Mapster.DependencyInjection" Version="1.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.17.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="6.0.13" />
    <PackageReference Include="Serilog.AspNetCore" Version="6.1.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EventsAndAssignments.Db\EventsAndAssignments.Db.csproj" />
    <ProjectReference Include="..\EventsAndAssignments.Infrastructure\EventsAndAssignments.Infrastructure.csproj" />
    <ProjectReference Include="..\EventsAndAssignments.Services\EventsAndAssignments.Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Recources\index.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DTO\Request\" />
  </ItemGroup>

</Project>
