<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.102.2" />
    <PackageReference Include="MailKit" Version="4.1.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="7.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EventsAndAssignments.Services\EventsAndAssignments.Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Resourse\" />
  </ItemGroup>

</Project>
