<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="3.2.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Mapster" Version="7.3.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.5.0" />
    <PackageReference Include="Moq" Version="4.20.70" />
    <PackageReference Include="NUnit" Version="3.13.3" />
    <PackageReference Include="NUnit.Analyzers" Version="3.6.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NUnit3TestAdapter" Version="4.4.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EventsAndAssignments.API\EventsAndAssignments.API.csproj" />
    <ProjectReference Include="..\EventsAndAssignments.Db\EventsAndAssignments.Db.csproj" />
    <ProjectReference Include="..\EventsAndAssignments.Infrastructure\EventsAndAssignments.Infrastructure.csproj" />
    <ProjectReference Include="..\EventsAndAssignments.Services\EventsAndAssignments.Services.csproj" />
	<ProjectReference Include="..\EventsAndAssignments.Models\EventsAndAssignments.Models.csproj" />
  </ItemGroup>

</Project>
