// <auto-generated />
using System;
using EventsAndAssignments.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventsAndAssignments.Db.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230803115849_AddExecutionDateFieldToNotifications")]
    partial class AddExecutionDateFieldToNotifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventsAndAssignments.Services.DAO.Assignment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExecutorExecutionDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("GroupId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InspectorCheckDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LeaderExecutionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("ProtocolId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Removed")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ResponsibleExecutorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ResponsibleInspectorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ResponsibleLeaderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("StatusId")
                        .HasColumnType("bigint");

                    b.Property<int>("Subversion")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ProtocolId");

                    b.HasIndex("ResponsibleExecutorId");

                    b.HasIndex("ResponsibleInspectorId");

                    b.HasIndex("ResponsibleLeaderId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("EventsAndAssignments.Services.DAO.AssignmentFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AssignmentId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OriginName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Removed")
                        .HasColumnType("datetime2");

                    b.Property<string>("SafetyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("EventsAndAssignments.Services.DAO.AssignmentHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AddedFile")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("AddedResponsibleExecutor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("AssignmentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("FromStatus")
                        .HasColumnType("bigint");

                    b.Property<int>("ModificationType")
                        .HasColumnType("int");

                    b.Property<long?>("RemovedFile")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("RemovedResponsibleExecutor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("ToStatus")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AddedFile");

                    b.HasIndex("AddedResponsibleExecutor");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("FromStatus");

                    b.HasIndex("RemovedFile");

                    b.HasIndex("RemovedResponsibleExecutor");

                    b.HasIndex("ToStatus");

                    b.ToTable("AssignmentHistories");
                });

            modelBuilder.Entity("EventsAndAssignments.Services.DAO.AssignmentStatus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsInShortLine")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AssignmentStatuses");
                });

            modelBuilder.Entity("EventsAndAssignments.Services.DAO.Comment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AssignmentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Removed")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("EventsAndAssignments.Services.DAO.Employee", b =>
                {
                    b.Property<Guid>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AnyLastModification")
                        .HasColumnType("datetime2")
                        .HasColumnName("AnyLastModfication");

                    b.Property<string>("DepartmentCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DepartmentLastModification")
                        .HasColumnType("datetime2")
                        .HasColumnName("DepartmentLastModfication");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Domain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EndDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HireDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsSfrelevant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Occupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrganizationLastModification")
                        .HasColumnType("datetime2")
                        .HasColumnName("OrganizationLastModfication");

                    b.Property<string>("OrganizationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PersonLastModification")
                        .HasColumnType("datetime2")
                        .HasColumnName("PersonLastModfication");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PhotoS")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PositionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PositionLastModification")
                        .HasColumnType("datetime2")
                        .HasColumnName("PositionLastModfication");

                    b.Property<string>("PositionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<string>("TabelNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PositionId");

                    b.HasIndex("RoleId");

                    b.ToTable("PuplicEmployeeViews");
                });

            modelBuilder.Entity("EventsAndAssignments.Services.DAO.EmployeeDirectory", b =>
                {
                    b.Property<string>("FullUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PositionId")
                        .HasColumnType("uniqueidentifier");

                    b.ToTable((string)null);

                    b.ToView("ViewEmployeeDirectory", (string)null);
                });

            modelBuilder.Entity("EventsAndAssignments.Services.DAO.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExecutionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit");

                    b.Property<long?>("PeriodicNotificationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SendDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PeriodicNotificationId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("EventsAndAssignments.Services.DAO.NotificationSetting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStatusChange")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWeekly")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserPositionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserPositionId");

                    b.ToTable("NotificationSettings");
                });

            modelBuilder.Entity("EventsAndAssignments.Services.DAO.Organization", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContatsName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DivisionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DivisionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GrounName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsCsrcompany")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsHiden")
                        .HasColumnType("bit");

                    b.Property<string>("IsNewMa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kskcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldOrganizationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Root")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UniqueId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrganizationId");

                    b.ToTable("PuplicOrganizationsView");
                });

            modelBuilder.Entity("EventsAndAssignments.Services.DAO.PeriodicNotification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AssignmentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ExecutionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RecipientPositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SendDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("RecipientPositionId");

                    b.ToTable("PeriodicNotifications");
                });

            modelBuilder.Entity("EventsAndAssignments.Services.DAO.Permission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "CreateFolder"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "ReadFolder"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "UpdateFolder"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "RemoveFolder"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "EmployeeIsInAssignment"
                        },
                        new
                        {
                            Id = 6L,
                            Name = "CreateProtocol"
                        },
                        new
                        {
                            Id = 7L,
                            Name = "ReadProtocol"
                        },
                        new
                        {
                            Id = 8L,
                            Name = "UpdateProtocol"
                        },
                        new
                        {
                            Id = 9L,
                            Name = "RemoveProtocol"
                        },
                        new
                        {
                            Id = 10L,
                            Name = "RemoveAssignment"
                        },
                        new
                        {
                            Id = 11L,
                            Name = "RemoveFile"
                        },
                        new
                        {
                            Id = 12L,
                            Name = "CreateAssignment"
                        });
                });

            modelBuilder.Entity("EventsAndAssignments.Services.DAO.Protocol", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("FolderId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Removed")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("FolderId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Protocols");
                });

            modelBuilder.Entity("EventsAndAssignments.Services.DAO.ProtocolFolder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Removed")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("ProtocolFolders");
                });

            modelBuilder.Entity("EventsAndAssignments.Services.DAO.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "SystemAdmin"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "SimpleUser"
                        });
                });

            modelBuilder.Entity("EventsAndAssignments.Services.DAO.RolePermission", b =>
                {
                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<long>("PermissionId")
                        .HasColumnType("bigint");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermission");

                    b.HasData(
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 1L
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 2L
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 3L
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 4L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 1L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 2L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 3L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 4L
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 6L
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 7L
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 8L
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 9L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 6L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 7L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 8L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 9L
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 10L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 10L
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 12L
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 12L
                        });
                });

            modelBuilder.Entity("EventsAndAssignments.Services.DAO.Assignment", b =>
                {
                    b.HasOne("EventsAndAssignments.Services.DAO.Employee", "Author")
                        .WithMany("AssignmentsAuthorNavigation")
                        .HasForeignKey("AuthorId");

                    b.HasOne("EventsAndAssignments.Services.DAO.Employee", "CreatedByNavigation")
                        .WithMany("AssignmentsCreatedByNavigation")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventsAndAssignments.Services.DAO.Organization", "Organization")
                        .WithMany("Assignments")
                        .HasForeignKey("OrganizationId");

                    b.HasOne("EventsAndAssignments.Services.DAO.Protocol", "Protocol")
                        .WithMany("Assignments")
                        .HasForeignKey("ProtocolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventsAndAssignments.Services.DAO.Employee", "ResponsibleExecutor")
                        .WithMany("AssignmentsResponsibleExecutorNavigation")
                        .HasForeignKey("ResponsibleExecutorId");

                    b.HasOne("EventsAndAssignments.Services.DAO.Employee", "ResponsibleInspector")
                        .WithMany("AssignmentsResponsibleInspectorNavigation")
                        .HasForeignKey("ResponsibleInspectorId");

                    b.HasOne("EventsAndAssignments.Services.DAO.Employee", "ResponsibleLeader")
                        .WithMany("AssignmentsResponsibleLeaderNavigation")
                        .HasForeignKey("ResponsibleLeaderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EventsAndAssignments.Services.DAO.AssignmentStatus", "Status")
                        .WithMany("Assignments")
                        .HasForeignKey("StatusId");

                    b.HasOne("EventsAndAssignments.Services.DAO.Employee", "UpdatedByNavigation")
                        .WithMany("AssignmentsUpdatedByNavigation")
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Author");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Organization");

                    b.Navigation("Protocol");

                    b.Navigation("ResponsibleExecutor");

                    b.Navigation("ResponsibleInspector");

                    b.Navigation("ResponsibleLeader");

                    b.Navigation("Status");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("EventsAndAssignments.Services.DAO.AssignmentFile", b =>
                {
                    b.HasOne("EventsAndAssignments.Services.DAO.Assignment", "Assignment")
                        .WithMany("Files")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventsAndAssignments.Services.DAO.Employee", "CreatedByNavigation")
                        .WithMany("AssignmentFilesCreatedByNavigation")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventsAndAssignments.Services.DAO.Employee", "UpdatedByNavigation")
                        .WithMany("AssignmentFilesUpdatedByNavigation")
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Assignment");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("EventsAndAssignments.Services.DAO.AssignmentHistory", b =>
                {
                    b.HasOne("EventsAndAssignments.Services.DAO.AssignmentFile", "AddedFileNavigation")
                        .WithMany("AssignmentHistoryAddedFileNavigations")
                        .HasForeignKey("AddedFile");

                    b.HasOne("EventsAndAssignments.Services.DAO.Employee", "AddedResponsibleExecutorNavigation")
                        .WithMany("AssignmentHistoryAddedResponsibleExecutorNavigation")
                        .HasForeignKey("AddedResponsibleExecutor");

                    b.HasOne("EventsAndAssignments.Services.DAO.Assignment", "Assignment")
                        .WithMany("History")
                        .HasForeignKey("AssignmentId");

                    b.HasOne("EventsAndAssignments.Services.DAO.Employee", "CreatedByNavigation")
                        .WithMany("AssignmentHistoryCreatedByNavigation")
                        .HasForeignKey("CreatedBy");

                    b.HasOne("EventsAndAssignments.Services.DAO.AssignmentStatus", "FromStatusNavigation")
                        .WithMany("AssignmentHistoryFromStatus")
                        .HasForeignKey("FromStatus");

                    b.HasOne("EventsAndAssignments.Services.DAO.AssignmentFile", "RemovedFileNavigation")
                        .WithMany("AssignmentHistoryDeletedFileNavigations")
                        .HasForeignKey("RemovedFile");

                    b.HasOne("EventsAndAssignments.Services.DAO.Employee", "RemovedResponsibleExecutorNavigation")
                        .WithMany("AssignmentHistoryRemovedResponsibleExecutorNavigation")
                        .HasForeignKey("RemovedResponsibleExecutor");

                    b.HasOne("EventsAndAssignments.Services.DAO.AssignmentStatus", "ToStatusNavigation")
                        .WithMany("AssignmentHistoryToStatus")
                        .HasForeignKey("ToStatus");

                    b.Navigation("AddedFileNavigation");

                    b.Navigation("AddedResponsibleExecutorNavigation");

                    b.Navigation("Assignment");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("FromStatusNavigation");

                    b.Navigation("RemovedFileNavigation");

                    b.Navigation("RemovedResponsibleExecutorNavigation");

                    b.Navigation("ToStatusNavigation");
                });

            modelBuilder.Entity("EventsAndAssignments.Services.DAO.Comment", b =>
                {
                    b.HasOne("EventsAndAssignments.Services.DAO.Assignment", "Assignment")
                        .WithMany("Comments")
                        .HasForeignKey("AssignmentId");

                    b.HasOne("EventsAndAssignments.Services.DAO.Employee", "CreatedByNavigation")
                        .WithMany("CommentsCreatedByNavigation")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventsAndAssignments.Services.DAO.Employee", "UpdatedByNavigation")
                        .WithMany("CommentsUpdatedByNavigation")
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Assignment");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("EventsAndAssignments.Services.DAO.Employee", b =>
                {
                    b.HasOne("EventsAndAssignments.Services.DAO.Role", "UserRole")
                        .WithMany("Employees")
                        .HasForeignKey("RoleId");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("EventsAndAssignments.Services.DAO.Notification", b =>
                {
                    b.HasOne("EventsAndAssignments.Services.DAO.PeriodicNotification", "PeriodicNotification")
                        .WithMany()
                        .HasForeignKey("PeriodicNotificationId");

                    b.Navigation("PeriodicNotification");
                });

            modelBuilder.Entity("EventsAndAssignments.Services.DAO.NotificationSetting", b =>
                {
                    b.HasOne("EventsAndAssignments.Services.DAO.Employee", "UserNavigation")
                        .WithMany("NotificationSettingUserNavigation")
                        .HasForeignKey("UserPositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserNavigation");
                });

            modelBuilder.Entity("EventsAndAssignments.Services.DAO.PeriodicNotification", b =>
                {
                    b.HasOne("EventsAndAssignments.Services.DAO.Assignment", "Assignment")
                        .WithMany()
                        .HasForeignKey("AssignmentId");

                    b.HasOne("EventsAndAssignments.Services.DAO.Employee", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientPositionId");

                    b.Navigation("Assignment");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("EventsAndAssignments.Services.DAO.Protocol", b =>
                {
                    b.HasOne("EventsAndAssignments.Services.DAO.Employee", "CreatedByNavigation")
                        .WithMany("ProtocolsCreatedByNavigation")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventsAndAssignments.Services.DAO.ProtocolFolder", "Folder")
                        .WithMany("Protocols")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventsAndAssignments.Services.DAO.Employee", "UpdatedByNavigation")
                        .WithMany("ProtocolsUpdatedByNavigation")
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Folder");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("EventsAndAssignments.Services.DAO.ProtocolFolder", b =>
                {
                    b.HasOne("EventsAndAssignments.Services.DAO.Employee", "CreatedByNavigation")
                        .WithMany("ProtocolFoldersCreatedByNavigation")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventsAndAssignments.Services.DAO.Employee", "UpdatedByNavigation")
                        .WithMany("ProtocolFoldersUpdatedByNavigation")
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("EventsAndAssignments.Services.DAO.RolePermission", b =>
                {
                    b.HasOne("EventsAndAssignments.Services.DAO.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventsAndAssignments.Services.DAO.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventsAndAssignments.Services.DAO.Assignment", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Files");

                    b.Navigation("History");
                });

            modelBuilder.Entity("EventsAndAssignments.Services.DAO.AssignmentFile", b =>
                {
                    b.Navigation("AssignmentHistoryAddedFileNavigations");

                    b.Navigation("AssignmentHistoryDeletedFileNavigations");
                });

            modelBuilder.Entity("EventsAndAssignments.Services.DAO.AssignmentStatus", b =>
                {
                    b.Navigation("AssignmentHistoryFromStatus");

                    b.Navigation("AssignmentHistoryToStatus");

                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("EventsAndAssignments.Services.DAO.Employee", b =>
                {
                    b.Navigation("AssignmentFilesCreatedByNavigation");

                    b.Navigation("AssignmentFilesUpdatedByNavigation");

                    b.Navigation("AssignmentHistoryAddedResponsibleExecutorNavigation");

                    b.Navigation("AssignmentHistoryCreatedByNavigation");

                    b.Navigation("AssignmentHistoryRemovedResponsibleExecutorNavigation");

                    b.Navigation("AssignmentsAuthorNavigation");

                    b.Navigation("AssignmentsCreatedByNavigation");

                    b.Navigation("AssignmentsResponsibleExecutorNavigation");

                    b.Navigation("AssignmentsResponsibleInspectorNavigation");

                    b.Navigation("AssignmentsResponsibleLeaderNavigation");

                    b.Navigation("AssignmentsUpdatedByNavigation");

                    b.Navigation("CommentsCreatedByNavigation");

                    b.Navigation("CommentsUpdatedByNavigation");

                    b.Navigation("NotificationSettingUserNavigation");

                    b.Navigation("ProtocolFoldersCreatedByNavigation");

                    b.Navigation("ProtocolFoldersUpdatedByNavigation");

                    b.Navigation("ProtocolsCreatedByNavigation");

                    b.Navigation("ProtocolsUpdatedByNavigation");
                });

            modelBuilder.Entity("EventsAndAssignments.Services.DAO.Organization", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("EventsAndAssignments.Services.DAO.Protocol", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("EventsAndAssignments.Services.DAO.ProtocolFolder", b =>
                {
                    b.Navigation("Protocols");
                });

            modelBuilder.Entity("EventsAndAssignments.Services.DAO.Role", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
